python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p1_q10.emb --iter 2 --p 1.0 --q 10.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p2_q9.emb --iter 2 --p 2.0 --q 9.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p3_q8.emb --iter 2 --p 3.0 --q 8.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p4_q7.emb --iter 2 --p 4.0 --q 7.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p5_q6.emb --iter 2 --p 5.0 --q 6.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p6_q5.emb --iter 2 --p 6.0 --q 5.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p7_q4.emb --iter 2 --p 7.0 --q 4.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p8_q3.emb --iter 2 --p 8.0 --q 3.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p9_q2.emb --iter 2 --p 9.0 --q 2.0 --weighted --directed
python src/main.py --input graph/trustedges10_scaled.csv --output emb/trust_m_p10_q1.emb --iter 2 --p 10.0 --q 1.0 --weighted --directed
